# This file was generated by GoReleaser. DO NOT EDIT.
cask "tpcli" do
  version "2.361.7"

  on_macos do
    on_intel do
      sha256 "6d9ac1eb4aac0f9d2d5e744ecdaf336745c2305918a9acb9e0030a0d2f7229d9"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f2cd454439b9bc2e022270aff9b3831aeb1409c521ef3f588cede305653cd30"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7a5fd61d6480ae4aaaac3910a44b58110cced69faad7618c176fadc7836c068"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d55b7a279e69e7123990103969167c7ac9bf5d14eaed31c2428d9ff3525fd55"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_linux_arm64.tar.gz"
    end
  end

  name "tpcli"
  desc "TestPlanner CLI"
  homepage "https://github.com/DocPlanner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tpcli"
  bash_completion "completions/tpcli.bash"
  fish_completion "completions/tpcli.fish"
  zsh_completion "completions/_tpcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tpcli"]
    end
  end

  # No zap stanza required

end
