# This file was generated by GoReleaser. DO NOT EDIT.
cask "tpcli" do
  version "2.385.15"

  on_macos do
    on_arm do
      sha256 "f6e46c86de63057ac6a8561b6c1fc758d534eb1c236defea930c90e38761483b"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b4546c48e3dd2460ca72429619e0fad40e65882051435a0ce14eb084bc703a8"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "70b3c5e97283fdebf3e560b2e7115e8d9b5cbff6254107c33c8d733a30070f0b"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "87868e8c86543acbeb57531cd8cf138de3fd2ab6b0b1b4baf72218ee74df77a3"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_linux_amd64.tar.gz"
    end
  end

  name "tpcli"
  desc "TestPlanner CLI"
  homepage "https://github.com/DocPlanner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tpcli"
  bash_completion "completions/tpcli.bash"
  fish_completion "completions/tpcli.fish"
  zsh_completion "completions/_tpcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tpcli"]
    end
  end

  # No zap stanza required
end
