# This file was generated by GoReleaser. DO NOT EDIT.
cask "tpcli" do
  version "2.349.1"

  on_macos do
    on_intel do
      sha256 "d69887d3da3c2c7391a7efc47b698e21bd8c5031e444351c3f4d3cac93aca5f9"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "752faaa0aea6e505988cf349582885b3a9c87d191a7f19d96d56d7dbef873772"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "287ecc3b76768e5e1676d8d20faaf24602ddcb718b4bd2285bd3e2e6269f1442"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "45191e47d789df2439fa44991255db30807106892653e5decda7b07352578653"
      url "https://github.com/DocPlanner/testplanner-releases/releases/download/#{version}/tpcli_linux_arm64.tar.gz"
    end
  end

  name "tpcli"
  desc "TestPlanner CLI"
  homepage "https://github.com/DocPlanner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tpcli"
  bash_completion "completions/tpcli.bash"
  fish_completion "completions/tpcli.fish"
  zsh_completion "completions/_tpcli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tpcli"]
    end
  end

  # No zap stanza required

end
